/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SamagriRouteImport } from './routes/samagri'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PanditsRouteImport } from './routes/pandits'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BecomePanditRouteImport } from './routes/become-pandit'
import { Route as AstrologyRouteImport } from './routes/astrology'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoojasIndexRouteImport } from './routes/poojas.index'
import { Route as PoojasSlugRouteImport } from './routes/poojas.$slug'
import { Route as AstrologyChatIdRouteImport } from './routes/astrology.chat.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SamagriRoute = SamagriRouteImport.update({
  id: '/samagri',
  path: '/samagri',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PanditsRoute = PanditsRouteImport.update({
  id: '/pandits',
  path: '/pandits',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePanditRoute = BecomePanditRouteImport.update({
  id: '/become-pandit',
  path: '/become-pandit',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyRoute = AstrologyRouteImport.update({
  id: '/astrology',
  path: '/astrology',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasIndexRoute = PoojasIndexRouteImport.update({
  id: '/poojas/',
  path: '/poojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasSlugRoute = PoojasSlugRouteImport.update({
  id: '/poojas/$slug',
  path: '/poojas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyChatIdRoute = AstrologyChatIdRouteImport.update({
  id: '/chat/$id',
  path: '/chat/$id',
  getParentRoute: () => AstrologyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRouteWithChildren
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/pandits': typeof PanditsRoute
  '/profile': typeof ProfileRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/poojas/': typeof PoojasIndexRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRouteWithChildren
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/pandits': typeof PanditsRoute
  '/profile': typeof ProfileRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/poojas': typeof PoojasIndexRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/astrology': typeof AstrologyRouteWithChildren
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/pandits': typeof PanditsRoute
  '/profile': typeof ProfileRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/poojas/': typeof PoojasIndexRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/astrology'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/pandits'
    | '/profile'
    | '/samagri'
    | '/signup'
    | '/poojas/$slug'
    | '/poojas/'
    | '/astrology/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/astrology'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/pandits'
    | '/profile'
    | '/samagri'
    | '/signup'
    | '/poojas/$slug'
    | '/poojas'
    | '/astrology/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/astrology'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/pandits'
    | '/profile'
    | '/samagri'
    | '/signup'
    | '/poojas/$slug'
    | '/poojas/'
    | '/astrology/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AstrologyRoute: typeof AstrologyRouteWithChildren
  BecomePanditRoute: typeof BecomePanditRoute
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  PanditsRoute: typeof PanditsRoute
  ProfileRoute: typeof ProfileRoute
  SamagriRoute: typeof SamagriRoute
  SignupRoute: typeof SignupRoute
  PoojasSlugRoute: typeof PoojasSlugRoute
  PoojasIndexRoute: typeof PoojasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samagri': {
      id: '/samagri'
      path: '/samagri'
      fullPath: '/samagri'
      preLoaderRoute: typeof SamagriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pandits': {
      id: '/pandits'
      path: '/pandits'
      fullPath: '/pandits'
      preLoaderRoute: typeof PanditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-pandit': {
      id: '/become-pandit'
      path: '/become-pandit'
      fullPath: '/become-pandit'
      preLoaderRoute: typeof BecomePanditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology': {
      id: '/astrology'
      path: '/astrology'
      fullPath: '/astrology'
      preLoaderRoute: typeof AstrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas/': {
      id: '/poojas/'
      path: '/poojas'
      fullPath: '/poojas/'
      preLoaderRoute: typeof PoojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas/$slug': {
      id: '/poojas/$slug'
      path: '/poojas/$slug'
      fullPath: '/poojas/$slug'
      preLoaderRoute: typeof PoojasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/chat/$id': {
      id: '/astrology/chat/$id'
      path: '/chat/$id'
      fullPath: '/astrology/chat/$id'
      preLoaderRoute: typeof AstrologyChatIdRouteImport
      parentRoute: typeof AstrologyRoute
    }
  }
}

interface AstrologyRouteChildren {
  AstrologyChatIdRoute: typeof AstrologyChatIdRoute
}

const AstrologyRouteChildren: AstrologyRouteChildren = {
  AstrologyChatIdRoute: AstrologyChatIdRoute,
}

const AstrologyRouteWithChildren = AstrologyRoute._addFileChildren(
  AstrologyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AstrologyRoute: AstrologyRouteWithChildren,
  BecomePanditRoute: BecomePanditRoute,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  PanditsRoute: PanditsRoute,
  ProfileRoute: ProfileRoute,
  SamagriRoute: SamagriRoute,
  SignupRoute: SignupRoute,
  PoojasSlugRoute: PoojasSlugRoute,
  PoojasIndexRoute: PoojasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
