/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SamagriRouteImport } from './routes/samagri'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as FestivalsRouteImport } from './routes/festivals'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BecomePanditRouteImport } from './routes/become-pandit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddressesRouteImport } from './routes/addresses'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoojasIndexRouteImport } from './routes/poojas.index'
import { Route as PanditsIndexRouteImport } from './routes/pandits.index'
import { Route as AstrologyIndexRouteImport } from './routes/astrology.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PoojasSlugRouteImport } from './routes/poojas.$slug'
import { Route as PanditsIdRouteImport } from './routes/pandits.$id'
import { Route as BookingNewRouteImport } from './routes/booking.new'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminPoojasRouteImport } from './routes/admin.poojas'
import { Route as AdminPanditsRouteImport } from './routes/admin.pandits'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminFestivalsRouteImport } from './routes/admin.festivals'
import { Route as AdminApplicationsRouteImport } from './routes/admin.applications'
import { Route as AstrologyChatIdRouteImport } from './routes/astrology.chat.$id'
import { Route as AstrologyCallIdRouteImport } from './routes/astrology.call.$id'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SamagriRoute = SamagriRouteImport.update({
  id: '/samagri',
  path: '/samagri',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const FestivalsRoute = FestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomePanditRoute = BecomePanditRouteImport.update({
  id: '/become-pandit',
  path: '/become-pandit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddressesRoute = AddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoojasIndexRoute = PoojasIndexRouteImport.update({
  id: '/poojas/',
  path: '/poojas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PanditsIndexRoute = PanditsIndexRouteImport.update({
  id: '/pandits/',
  path: '/pandits/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyIndexRoute = AstrologyIndexRouteImport.update({
  id: '/astrology/',
  path: '/astrology/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PoojasSlugRoute = PoojasSlugRouteImport.update({
  id: '/poojas/$slug',
  path: '/poojas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PanditsIdRoute = PanditsIdRouteImport.update({
  id: '/pandits/$id',
  path: '/pandits/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingNewRoute = BookingNewRouteImport.update({
  id: '/booking/new',
  path: '/booking/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPoojasRoute = AdminPoojasRouteImport.update({
  id: '/poojas',
  path: '/poojas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPanditsRoute = AdminPanditsRouteImport.update({
  id: '/pandits',
  path: '/pandits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFestivalsRoute = AdminFestivalsRouteImport.update({
  id: '/festivals',
  path: '/festivals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminApplicationsRoute = AdminApplicationsRouteImport.update({
  id: '/applications',
  path: '/applications',
  getParentRoute: () => AdminRoute,
} as any)
const AstrologyChatIdRoute = AstrologyChatIdRouteImport.update({
  id: '/astrology/chat/$id',
  path: '/astrology/chat/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologyCallIdRoute = AstrologyCallIdRouteImport.update({
  id: '/astrology/call/$id',
  path: '/astrology/call/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/festivals': typeof FestivalsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pandits': typeof AdminPanditsRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/new': typeof BookingNewRoute
  '/pandits/$id': typeof PanditsIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/pandits/': typeof PanditsIndexRoute
  '/poojas/': typeof PoojasIndexRoute
  '/astrology/call/$id': typeof AstrologyCallIdRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/festivals': typeof FestivalsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pandits': typeof AdminPanditsRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/new': typeof BookingNewRoute
  '/pandits/$id': typeof PanditsIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/astrology': typeof AstrologyIndexRoute
  '/pandits': typeof PanditsIndexRoute
  '/poojas': typeof PoojasIndexRoute
  '/astrology/call/$id': typeof AstrologyCallIdRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/addresses': typeof AddressesRoute
  '/admin': typeof AdminRouteWithChildren
  '/become-pandit': typeof BecomePanditRoute
  '/bookings': typeof BookingsRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/festivals': typeof FestivalsRoute
  '/orders': typeof OrdersRoute
  '/profile': typeof ProfileRoute
  '/refer': typeof ReferRoute
  '/samagri': typeof SamagriRoute
  '/signup': typeof SignupRoute
  '/wallet': typeof WalletRoute
  '/welcome': typeof WelcomeRoute
  '/admin/applications': typeof AdminApplicationsRoute
  '/admin/festivals': typeof AdminFestivalsRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/pandits': typeof AdminPanditsRoute
  '/admin/poojas': typeof AdminPoojasRoute
  '/admin/users': typeof AdminUsersRoute
  '/booking/new': typeof BookingNewRoute
  '/pandits/$id': typeof PanditsIdRoute
  '/poojas/$slug': typeof PoojasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/astrology/': typeof AstrologyIndexRoute
  '/pandits/': typeof PanditsIndexRoute
  '/poojas/': typeof PoojasIndexRoute
  '/astrology/call/$id': typeof AstrologyCallIdRoute
  '/astrology/chat/$id': typeof AstrologyChatIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/addresses'
    | '/admin'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/checkout'
    | '/festivals'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/samagri'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/admin/applications'
    | '/admin/festivals'
    | '/admin/orders'
    | '/admin/pandits'
    | '/admin/poojas'
    | '/admin/users'
    | '/booking/new'
    | '/pandits/$id'
    | '/poojas/$slug'
    | '/admin/'
    | '/astrology/'
    | '/pandits/'
    | '/poojas/'
    | '/astrology/call/$id'
    | '/astrology/chat/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/addresses'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/checkout'
    | '/festivals'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/samagri'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/admin/applications'
    | '/admin/festivals'
    | '/admin/orders'
    | '/admin/pandits'
    | '/admin/poojas'
    | '/admin/users'
    | '/booking/new'
    | '/pandits/$id'
    | '/poojas/$slug'
    | '/admin'
    | '/astrology'
    | '/pandits'
    | '/poojas'
    | '/astrology/call/$id'
    | '/astrology/chat/$id'
  id:
    | '__root__'
    | '/'
    | '/addresses'
    | '/admin'
    | '/become-pandit'
    | '/bookings'
    | '/cart'
    | '/checkout'
    | '/festivals'
    | '/orders'
    | '/profile'
    | '/refer'
    | '/samagri'
    | '/signup'
    | '/wallet'
    | '/welcome'
    | '/admin/applications'
    | '/admin/festivals'
    | '/admin/orders'
    | '/admin/pandits'
    | '/admin/poojas'
    | '/admin/users'
    | '/booking/new'
    | '/pandits/$id'
    | '/poojas/$slug'
    | '/admin/'
    | '/astrology/'
    | '/pandits/'
    | '/poojas/'
    | '/astrology/call/$id'
    | '/astrology/chat/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddressesRoute: typeof AddressesRoute
  AdminRoute: typeof AdminRouteWithChildren
  BecomePanditRoute: typeof BecomePanditRoute
  BookingsRoute: typeof BookingsRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  FestivalsRoute: typeof FestivalsRoute
  OrdersRoute: typeof OrdersRoute
  ProfileRoute: typeof ProfileRoute
  ReferRoute: typeof ReferRoute
  SamagriRoute: typeof SamagriRoute
  SignupRoute: typeof SignupRoute
  WalletRoute: typeof WalletRoute
  WelcomeRoute: typeof WelcomeRoute
  BookingNewRoute: typeof BookingNewRoute
  PanditsIdRoute: typeof PanditsIdRoute
  PoojasSlugRoute: typeof PoojasSlugRoute
  AstrologyIndexRoute: typeof AstrologyIndexRoute
  PanditsIndexRoute: typeof PanditsIndexRoute
  PoojasIndexRoute: typeof PoojasIndexRoute
  AstrologyCallIdRoute: typeof AstrologyCallIdRoute
  AstrologyChatIdRoute: typeof AstrologyChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/samagri': {
      id: '/samagri'
      path: '/samagri'
      fullPath: '/samagri'
      preLoaderRoute: typeof SamagriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/festivals': {
      id: '/festivals'
      path: '/festivals'
      fullPath: '/festivals'
      preLoaderRoute: typeof FestivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-pandit': {
      id: '/become-pandit'
      path: '/become-pandit'
      fullPath: '/become-pandit'
      preLoaderRoute: typeof BecomePanditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/addresses': {
      id: '/addresses'
      path: '/addresses'
      fullPath: '/addresses'
      preLoaderRoute: typeof AddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/poojas/': {
      id: '/poojas/'
      path: '/poojas'
      fullPath: '/poojas/'
      preLoaderRoute: typeof PoojasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pandits/': {
      id: '/pandits/'
      path: '/pandits'
      fullPath: '/pandits/'
      preLoaderRoute: typeof PanditsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/': {
      id: '/astrology/'
      path: '/astrology'
      fullPath: '/astrology/'
      preLoaderRoute: typeof AstrologyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/poojas/$slug': {
      id: '/poojas/$slug'
      path: '/poojas/$slug'
      fullPath: '/poojas/$slug'
      preLoaderRoute: typeof PoojasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pandits/$id': {
      id: '/pandits/$id'
      path: '/pandits/$id'
      fullPath: '/pandits/$id'
      preLoaderRoute: typeof PanditsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/new': {
      id: '/booking/new'
      path: '/booking/new'
      fullPath: '/booking/new'
      preLoaderRoute: typeof BookingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/poojas': {
      id: '/admin/poojas'
      path: '/poojas'
      fullPath: '/admin/poojas'
      preLoaderRoute: typeof AdminPoojasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pandits': {
      id: '/admin/pandits'
      path: '/pandits'
      fullPath: '/admin/pandits'
      preLoaderRoute: typeof AdminPanditsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/festivals': {
      id: '/admin/festivals'
      path: '/festivals'
      fullPath: '/admin/festivals'
      preLoaderRoute: typeof AdminFestivalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/applications': {
      id: '/admin/applications'
      path: '/applications'
      fullPath: '/admin/applications'
      preLoaderRoute: typeof AdminApplicationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/astrology/chat/$id': {
      id: '/astrology/chat/$id'
      path: '/astrology/chat/$id'
      fullPath: '/astrology/chat/$id'
      preLoaderRoute: typeof AstrologyChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrology/call/$id': {
      id: '/astrology/call/$id'
      path: '/astrology/call/$id'
      fullPath: '/astrology/call/$id'
      preLoaderRoute: typeof AstrologyCallIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminApplicationsRoute: typeof AdminApplicationsRoute
  AdminFestivalsRoute: typeof AdminFestivalsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPanditsRoute: typeof AdminPanditsRoute
  AdminPoojasRoute: typeof AdminPoojasRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminApplicationsRoute: AdminApplicationsRoute,
  AdminFestivalsRoute: AdminFestivalsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPanditsRoute: AdminPanditsRoute,
  AdminPoojasRoute: AdminPoojasRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddressesRoute: AddressesRoute,
  AdminRoute: AdminRouteWithChildren,
  BecomePanditRoute: BecomePanditRoute,
  BookingsRoute: BookingsRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  FestivalsRoute: FestivalsRoute,
  OrdersRoute: OrdersRoute,
  ProfileRoute: ProfileRoute,
  ReferRoute: ReferRoute,
  SamagriRoute: SamagriRoute,
  SignupRoute: SignupRoute,
  WalletRoute: WalletRoute,
  WelcomeRoute: WelcomeRoute,
  BookingNewRoute: BookingNewRoute,
  PanditsIdRoute: PanditsIdRoute,
  PoojasSlugRoute: PoojasSlugRoute,
  AstrologyIndexRoute: AstrologyIndexRoute,
  PanditsIndexRoute: PanditsIndexRoute,
  PoojasIndexRoute: PoojasIndexRoute,
  AstrologyCallIdRoute: AstrologyCallIdRoute,
  AstrologyChatIdRoute: AstrologyChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
