-- Loose samagri items from the workbook (Packaging Material sheet). The sheet has
-- no prices, so these are estimated placeholders. Imported as inactive drafts
-- (active = false); review prices and images, then publish from the Store SKUs
-- screen. Duplicate slugs are skipped.

INSERT INTO public.store_skus (name, slug, description, category, price_paise, mrp_paise, stock, active, sort_order, tags) VALUES
('Gangajal', 'gangajal', 'Gangajal, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 0, '{}'::text[]),
('Panchamrit (Milk/Curd/Honey/Ghee/Sugar)', 'panchamrit-milk-curd-honey-ghee-sugar', 'Panchamrit (Milk/Curd/Honey/Ghee/Sugar), packed fresh for your pooja.', 'samagri', 9900, 13000, 100, false, 1, '{}'::text[]),
('Ghee', 'ghee', 'Ghee, packed fresh for your pooja.', 'samagri', 9900, 13000, 100, false, 2, '{}'::text[]),
('Gulab Jal', 'gulab-jal', 'Gulab Jal, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 3, '{}'::text[]),
('Aromatherapy Oil', 'aromatherapy-oil', 'Aromatherapy Oil, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 4, '{}'::text[]),
('Sesame Oil / Coconut Oil (Diya)', 'sesame-oil-coconut-oil-diya', 'Sesame Oil / Coconut Oil (Diya), packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 5, '{}'::text[]),
('Kumkum / Sindoor', 'kumkum-sindoor', 'Kumkum / Sindoor, packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 6, '{}'::text[]),
('Haldi (Turmeric)', 'haldi-turmeric', 'Haldi (Turmeric), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 7, '{}'::text[]),
('Roli', 'roli', 'Roli, packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 8, '{}'::text[]),
('Akshat (Rice)', 'akshat-rice', 'Akshat (Rice), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 9, '{}'::text[]),
('Bhasma (Sacred Ash)', 'bhasma-sacred-ash', 'Bhasma (Sacred Ash), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 10, '{}'::text[]),
('Kesar (Saffron)', 'kesar-saffron', 'Kesar (Saffron), packed fresh for your pooja.', 'samagri', 14900, 19000, 100, false, 11, '{}'::text[]),
('Chandan (Sandalwood Powder)', 'chandan-sandalwood-powder', 'Chandan (Sandalwood Powder), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 12, '{}'::text[]),
('Ashtagandha', 'ashtagandha', 'Ashtagandha, packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 13, '{}'::text[]),
('Mishri (Rock Sugar)', 'mishri-rock-sugar', 'Mishri (Rock Sugar), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 14, '{}'::text[]),
('Havan Samagri Mix', 'havan-samagri-mix', 'Havan Samagri Mix, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 15, '{}'::text[]),
('Navadhanya Grains (9 types)', 'navadhanya-grains-9-types', 'Navadhanya Grains (9 types), packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 16, '{}'::text[]),
('Rangoli Colors', 'rangoli-colors', 'Rangoli Colors, packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 17, '{}'::text[]),
('Sesame (Til) / Barley (Jau)', 'sesame-til-barley-jau', 'Sesame (Til) / Barley (Jau), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 18, '{}'::text[]),
('Bel Patra', 'bel-patra', 'Bel Patra, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 19, '{}'::text[]),
('Tulsi Leaves', 'tulsi-leaves', 'Tulsi Leaves, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 20, '{}'::text[]),
('Mango Leaves', 'mango-leaves', 'Mango Leaves, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 21, '{}'::text[]),
('Betel Leaves', 'betel-leaves', 'Betel Leaves, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 22, '{}'::text[]),
('Durva Grass', 'durva-grass', 'Durva Grass, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 23, '{}'::text[]),
('Kusha Grass', 'kusha-grass', 'Kusha Grass, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 24, '{}'::text[]),
('Neem Leaves', 'neem-leaves', 'Neem Leaves, packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 25, '{}'::text[]),
('Flowers (Fresh)', 'flowers-fresh', 'Flowers (Fresh), packed fresh for your pooja.', 'samagri', 2900, 4000, 100, false, 26, '{}'::text[]),
('Camphor (Kapoor)', 'camphor-kapoor', 'Camphor (Kapoor), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 27, '{}'::text[]),
('Dhoop (Incense Cones/Sticks)', 'dhoop-incense-cones-sticks', 'Dhoop (Incense Cones/Sticks), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 28, '{}'::text[]),
('Incense Sticks (Agarbatti)', 'incense-sticks-agarbatti', 'Incense Sticks (Agarbatti), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 29, '{}'::text[]),
('Chandan (Sandalwood Stick)', 'chandan-sandalwood-stick', 'Chandan (Sandalwood Stick), packed fresh for your pooja.', 'samagri', 3900, 5000, 100, false, 30, '{}'::text[]),
('Shivling (small)', 'shivling-small', 'Shivling (small), packed fresh for your pooja.', 'samagri', 29900, 39000, 100, false, 31, '{}'::text[]),
('Vishnu Idol / Devi Idol / Ganesh Idol', 'vishnu-idol-devi-idol-ganesh-idol', 'Vishnu Idol / Devi Idol / Ganesh Idol, packed fresh for your pooja.', 'samagri', 29900, 39000, 100, false, 32, '{}'::text[]),
('Kalash (Brass)', 'kalash-brass', 'Kalash (Brass), packed fresh for your pooja.', 'samagri', 24900, 32000, 100, false, 33, '{}'::text[]),
('Copper Water Vessel', 'copper-water-vessel', 'Copper Water Vessel, packed fresh for your pooja.', 'samagri', 24900, 32000, 100, false, 34, '{}'::text[]),
('Glass Bottle (Gangajal/Gulab Jal)', 'glass-bottle-gangajal-gulab-jal', 'Glass Bottle (Gangajal/Gulab Jal), packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 35, '{}'::text[]),
('Aarti Thali', 'aarti-thali', 'Aarti Thali, packed fresh for your pooja.', 'samagri', 24900, 32000, 100, false, 36, '{}'::text[]),
('Healing Crystal', 'healing-crystal', 'Healing Crystal, packed fresh for your pooja.', 'samagri', 14900, 19000, 100, false, 37, '{}'::text[]),
('Diya (Clay)', 'diya-clay', 'Diya (Clay), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 38, '{}'::text[]),
('Cloth (Red/Yellow/White/Colored)', 'cloth-red-yellow-white-colored', 'Cloth (Red/Yellow/White/Colored), packed fresh for your pooja.', 'samagri', 9900, 13000, 100, false, 39, '{}'::text[]),
('Chunri / Saree', 'chunri-saree', 'Chunri / Saree, packed fresh for your pooja.', 'samagri', 14900, 19000, 100, false, 40, '{}'::text[]),
('Janeu (Sacred Thread)', 'janeu-sacred-thread', 'Janeu (Sacred Thread), packed fresh for your pooja.', 'samagri', 1900, 2000, 100, false, 41, '{}'::text[]),
('Moli (Red Thread)', 'moli-red-thread', 'Moli (Red Thread), packed fresh for your pooja.', 'samagri', 1900, 2000, 100, false, 42, '{}'::text[]),
('Cotton Wicks', 'cotton-wicks', 'Cotton Wicks, packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 43, '{}'::text[]),
('Modak / Ladoo', 'modak-ladoo', 'Modak / Ladoo, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 44, '{}'::text[]),
('Dry Fruits', 'dry-fruits', 'Dry Fruits, packed fresh for your pooja.', 'samagri', 7900, 10000, 100, false, 45, '{}'::text[]),
('Coconut (whole)', 'coconut-whole', 'Coconut (whole), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 46, '{}'::text[]),
('Betel Nuts (Supari)', 'betel-nuts-supari', 'Betel Nuts (Supari), packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 47, '{}'::text[]),
('Havan Kund', 'havan-kund', 'Havan Kund, packed fresh for your pooja.', 'samagri', 24900, 32000, 100, false, 48, '{}'::text[]),
('Mango Wood (for Havan)', 'mango-wood-for-havan', 'Mango Wood (for Havan), packed fresh for your pooja.', 'samagri', 9900, 13000, 100, false, 49, '{}'::text[]),
('Rudraksha (beads/mala)', 'rudraksha-beads-mala', 'Rudraksha (beads/mala), packed fresh for your pooja.', 'samagri', 24900, 32000, 100, false, 50, '{}'::text[]),
('Coins', 'coins', 'Coins, packed fresh for your pooja.', 'samagri', 4900, 6000, 100, false, 51, '{}'::text[]),
('Matchbox', 'matchbox', 'Matchbox, packed fresh for your pooja.', 'samagri', 900, 1000, 100, false, 52, '{}'::text[])
ON CONFLICT (slug) DO NOTHING;
